# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plats.Menu'),
            preserve_default=False,
        ),
    ]
